// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM24RzooaUt2QjlTygk7P1atRDchPKnDM',
    appId: '1:321807548465:web:7f767ce7188aea8eefd510',
    messagingSenderId: '321807548465',
    projectId: 'it363-2cd9b',
    authDomain: 'it363-2cd9b.firebaseapp.com',
    storageBucket: 'it363-2cd9b.firebasestorage.app',
    measurementId: 'G-1CSSPTF77S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAFo33AxoHPilrVFmw0fIjhmh90NrqcQ',
    appId: '1:321807548465:android:59c9b8ca08f295e0efd510',
    messagingSenderId: '321807548465',
    projectId: 'it363-2cd9b',
    storageBucket: 'it363-2cd9b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM24RzooaUt2QjlTygk7P1atRDchPKnDM',
    appId: '1:321807548465:web:f1c8573c0bee8f3befd510',
    messagingSenderId: '321807548465',
    projectId: 'it363-2cd9b',
    authDomain: 'it363-2cd9b.firebaseapp.com',
    storageBucket: 'it363-2cd9b.firebasestorage.app',
    measurementId: 'G-S77W57QBYS',
  );
}